# DEV CONFIG
spring.datasource.username=postgres
spring.datasource.password=2025

# Hibernate  properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logger details
logging.level.org.hibernate=DEBUG
logging.level.com.zaxxer.hikari=INFO
logging.file.path=E:/logs


