
# auth-service-dev.properties
logging.level.org.springframework.security=DEBUG
logging.level.com.authservice=DEBUG
merchant.url.boxcharge=https://console.boxchrge.com
merchant.url.pgx=https://pgx.i15.biz
merchant.url.localhost=http://localhost:3001
spring.web.merchant-url=https://console.boxchrge.com

