# =========================
# Default Mail Provider
# =========================
spring.mailapi.switch-api-name=juvlon

# -------------------------------
# Brevo Mail API configuration
spring.mailapi.brevo.api-name=Brevo
spring.mailapi.brevo.api-url=https://api.brevo.com/v3/smtp/email
spring.mailapi.brevo.api-key=xkeysib-your-brevo-key-here
spring.mailapi.brevo.api-from=noreply@boxchrge.com

# -------------------------------
# Juvlon Mail API configuration
spring.mailapi.juvlon.api-name=Juvlon
spring.mailapi.juvlon.api-url=https://api2.juvlon.com/v5/sendEmail
spring.mailapi.juvlon.api-key=MTA1MTUxIyMjMjAyNS0wNS0wOCAxNjo0OTozOQ==
spring.mailapi.juvlon.api-from=it@paywb.co

